packages:
  - 'microservice/auth-service/src'
  - 'microservice/cache-service/src'
  - 'microservice/core-service/src'
  - 'microservice/gateway-service'
  - 'microservice/common'
  - 'microservice/frontend'
  - 'script'
