module.exports = {
    CREATE_AGENDA_JOB_MQ_QUEUE: "CREATE_AGENDA_JOB",
    CANCEL_AGENDA_JOB_MQ_QUEUE: "CANCEL_AGENDA_JOB",

    PROCESS_LOG_ALERT_MQ_QUEUE: "PROCESS_LOG_ALERT",
    PROCESS_SEND_WEBHOOK_MQ_QUEUE: "PROCESS_SEND_WEBHOOK"
}