export const API_HOST = import.meta.env.VITE_API_HOST;
export const PROJECT_TITLE = import.meta.env.VITE_PROJECT_TITLE

export const SUCCESS_ERR_CODE = 200;
export const SUCCESS_ERR_MESSAGE = "Success";

export const UNKNOWN_ERR_CODE = 500;
export const UNKNOWN_ERR_MESSAGE = "Unknown Error";

export const NOT_FOUND_ERR_CODE = 404;
export const NOT_FOUND_ERR_MESSAGE = "Not Found";

export const NO_ACCESS_ERR_CODE = 401;
export const NO_ACCESS_ERR_MESSAGE = "No Access";

export const INVALID_INPUT_ERR_CODE = 400;
export const INVALID_INPUT_ERR_MESSAGE = "Bad Request";

export const EMAIL_PASSWORD_LOGIN_TYPE = "EMAIL_PASSWORD"

export const PENDING_FLASH_SALE_STATUS = "PENDING"
export const ACTIVE_FLASH_SALE_STATUS = "ACTIVE"
export const FINISHED_FLASH_SALE_STATUS = "FINISHED"

export const ORDER_RESULT_SOCKETIO_CHANNEL = "ORDER_RESULT"

export const WRITE_USER_INVITATION_USER_ROLE = "WRITE_USER_INVITATION"
export const READ_USER_INVITATION_USER_ROLE = "READ_USER_INVITATION"

// User Management
export const WRITE_USER_USER_ROLE = "WRITE_USER"
export const READ_USER_USER_ROLE = "READ_USER"


export const WRITE_PROJECT_ROLE = "WRITE_PROJECT"
export const READ_PROJECT_ROLE = "READ_PROJECT"

export const WRITE_REPORT_USER_ROLE = "WRITE_REPORT"
export const READ_REPORT_USER_ROLE = "READ_REPORT"

export const WRITE_WEBHOOK_USER_ROLE = "WRITE_WEBHOOK"
export const READ_WEBHOOK_USER_ROLE = "READ_WEBHOOK"


export const ERROR_LOG_LEVEL = "ERROR"
export const INFO_LOG_LEVEL = "INFO"
export const WARNING_LOG_LEVEL = "WARNING"
export const CRITICAL_LOG_LEVEL = "CRITICAL"
export const SUCCESS_LOG_LEVEL = "SUCCESS"
export const DEAD_LETTER_QUEUE_LOG_LEVEL = "DEAD_LETTER_QUEUE"

export const FULL_PAYLOAD_DEDUPLICATION_STRATEGY = "FULL_PAYLOAD"
export const INDEX_ONLY_DEDUPLICATION_STRATEGY = "INDEX_ONLY"
export const NONE_DEDUPLICATION_STRATEGY = "NONE"

export const BEARER_PROBE_AUTH_TYPE = "BEARER"
export const BASIC_PROBE_AUTH_TYPE = "BASIC"
export const PROBESTYX_PROBE_AUTH_TYPE = "PROBESTYX"
export const HMAC_PROBE_AUTH_TYPE = "HMAC"
export const NONE_PROBE_AUTH_TYPE = "NONE"
export const CUSTOM_PROBE_AUTH_TYPE = "CUSTOM"

export const PRIVATE_REPORT_VISIBILITY = "PRIVATE"
export const PUBLIC_REPORT_VISIBILITY = "PUBLIC"
export const UNLISTED_REPORT_VISIBILITY = "UNLISTED"

export const NONE_WEBHOOK_AUTH_TYPE = "NONE"
export const BEARER_WEBHOOK_AUTH_TYPE = "BEARER"
export const BASIC_WEBHOOK_AUTH_TYPE = "BASIC"
export const API_KEY_WEBHOOK_AUTH_TYPE = "API_KEY"
