// @ts-check 

module.exports = {
    CREATE_LOG_WSROUTE: "CREATE_LOG",
    GET_USER_PROJECT_STATS_WSROUTE: "GET_USER_PROJECT_STATS",
    GET_USER_BUCKET_STATS_WSROUTE: "GET_USER_BUCKET_STATS",
    LIST_USER_PROJECT_WSROUTE: "LIST_USER_PROJECT",
    LIST_USER_BUCKET_WSROUTE: "LIST_USER_BUCKET",
    FIND_PROJECT_BY_ID_WSROUTE: "FIND_PROJECT_BY_ID",
    FIND_BUCKET_BY_ID_WSROUTE: "FIND_BUCKET_BY_ID",
    PAGINATE_PROJECT_WSROUTE: "PAGINATE_PROJECT",
    PAGINATE_BUCKET_WSROUTE: "PAGINATE_BUCKET"
}