// @ts-check 

module.exports = {
    CREATE_LOG_WSROUTE: "CREATE_LOG",
    GET_USER_DASHBOARD_PROJECT_STATS_WSROUTE:"GET_USER_DASHBOARD_PROJECT_STATS",
    LIST_USER_PROJECT_WSROUTE:"LIST_USER_PROJECT"
}