module.exports = {
    BEARER_MIDDLEWARE_VALIDATION_SOURCE: "BEARER",
    COOKIE_MIDDLEWARE_VALIDATION_SOURCE: "COOKIE",
    SIGNATURE_MIDDLEWARE_VALIDATION_SOURCE: "SIGNATURE",


    // User Management
    WRITE_USER_INVITATION_USER_ROLE: "WRITE_USER_INVITATION",
    READ_USER_INVITATION_USER_ROLE: "READ_USER_INVITATION",

    // User Management
    WRITE_USER_USER_ROLE: "WRITE_USER",
    READ_USER_USER_ROLE: "READ_USER",

    // Project Management
    WRITE_PROJECT_USER_ROLE: "WRITE_PROJECT",
    READ_PROJECT_USER_ROLE: "READ_PROJECT",

    WRITE_BUCKET_USER_ROLE: "WRITE_BUCKET",
    READ_BUCKET_USER_ROLE: "READ_BUCKET",

    WRITE_WEBHOOK_USER_ROLE: "WRITE_WEBHOOK",
    READ_WEBHOOK_USER_ROLE: "READ_WEBHOOK",

    WRITE_ALERT_USER_ROLE: "WRITE_ALERT",
    READ_ALERT_USER_ROLE: "READ_ALERT",

    WRITE_REPORT_USER_ROLE: "WRITE_REPORT",
    READ_REPORT_USER_ROLE: "READ_REPORT",

    REFRESH_TOKEN_COOKIE_NAME: "REFRESH_TOKEN",
    ADMIN_TOKEN_COOKIE_NAME: "ADMIN_COOKIE",
    USER_TOKEN_COOKIE_NAME: "USER_TOKEN",

    CREATE_COOKIE_OPTION: {
        maxAge: 1000 * 60 * 60, // 1 hour
        httpOnly: true,
        sameSite: 'lax',
        secure: false
    },

    CLEAR_COOKIE_OPTION: {
        httpOnly: true,
        sameSite: 'lax',
        secure: false
    },
    BROWSER_CLIENT_TYPE: "browser",

    EMAIL_PASSWORD_LOGIN_TYPE: "EMAIL_PASSWORD"
}