module.exports = {
    USER_CACHE_KEY: "USER",
    USER_LOGIN_CACHE_KEY: "USER_LOGIN",

    PROJECT_CACHE_KEY: "PROJECT",
    PROBE_CACHE_KEY: "PROBE",

    WIDGET_CACHE_KEY: "WIDGET",
    REPORT_CACHE_KEY: "REPORT",
    WIDGET_DATA_CACHE_KEY: "WIDGET_DATA",

    WEBHOOK_CACHE_KEY:"WEBHOOK",
    ALERT_CACHE_KEY:"ALERT",
}