module.exports = {
    FULL_PAYLOAD_DEDUPLICATION_STRATEGY: "FULL_PAYLOAD",
    INDEX_ONLY_DEDUPLICATION_STRATEGY:"INDEX_ONLY",
    NONE_DEDUPLICATION_STRATEGY:"NONE",

    ACTIVE_PROBE_STATUS:"ACTIVE",
    PAUSED_PROBE_STATUS:"PAUSED",

    BEARER_PROBE_AUTH_TYPE:"BEARER",
    BASIC_PROBE_AUTH_TYPE:"BASIC",
    PROBESTYX_PROBE_AUTH_TYPE:"PROBESTYX",
    HMAC_PROBE_AUTH_TYPE:"HMAC",
    NONE_PROBE_AUTH_TYPE:"NONE",
    CUSTOM_PROBE_AUTH_TYPE:"CUSTOM",

    PROBE_LOG_CONTEXT_SOURCE:"PROBE"

}