//@ts-check

module.exports={
    SUCCESS_ERR_CODE:200,
    UNKNOWN_ERR_CODE:500,
    NO_ACCESS_ERR_CODE:401,
    NOT_FOUND_ERR_CODE:404,
    INVALID_INPUT_ERR_CODE:400,

    WS_CONNECTION_ERR_CODE:"WS_ERROR",
    MQ_CONNECTION_ERR_CODE:"MQ_ERROR",

    SUCCESS_ERR_MESSAGE:"Success",
    NO_ACCESS_ERR_MESSAGE:"Unauthorize Access",
    UNKNOWN_ERR_MESSAGE:"Unknown Error",
    NOT_FOUND_ERR_MESSAGE:"Not Found",
    INVALID_INPUT_ERR_MESSAGE:"Bad Request",
    MQ_NOT_READY_ERR_MESSAGE:"MQ Not Ready",

    USER_NOT_FOUND_ERR_MESSAGE:"User Not Found",
    PROJECT_NOT_FOUND_ERR_MESSAGE:"Project Not Found",
    ALREADY_A_MEMBER_ERR_MESSAGE:"Already a member",
    NOT_A_MEMBER_ERR_MESSAGE:"Not a member",

    ERROR_LOG_LEVEL:"ERROR",
    INFO_LOG_LEVEL:"INFO",
    WARNING_LOG_LEVEL:"WARNING",
    CRITICAL_LOG_LEVEL:"CRITICAL",
    SUCCESS_LOG_LEVEL:"SUCCESS",
    DEAD_LETTER_QUEUE_LOG_LEVEL:"DEAD_LETTER_QUEUE",

    INVALID_EMAIL_PASSWORD_ERR_MESSAGE:`You have entered an invalid password or email`,
    INVALID_AUTHENTICATOR_TOKEN_ERR_MESSAGE:`Invalid token`
}