module.exports = {
    ALLOWED_HTML_TAGS: ["a", "u", "p", "div", "strong", "b", "span", "ul", "ol", "li", "img", "iframe"],

    SUBMIT_MESSAGE_QUEUE_AGENDA_JOB: "SUBMIT_MESSAGE_QUEUE",
    SUBMIT_MESSAGE_FANOUT_AGENDA_JOB: "SUBMIT_MESSAGE_FANOUT",

    NONE_WEBHOOK_AUTH_TYPE: "NONE",
    BEARER_WEBHOOK_AUTH_TYPE: "BEARER",
    BASIC_WEBHOOK_AUTH_TYPE: "BASIC",
    API_KEY_WEBHOOK_AUTH_TYPE: "API_KEY",

}